# Generated by Django 5.1.6 on 2025-06-19 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 6, 19, 23, 9, 1, 423150, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
